### ISSUE TITLE
Version 0.9.0 Strategic Permian Demo (default) error

### ISSUE THREAD

**Issue by dangunter** [project-pareto/pareto-ui#55] opened 2024-01-11 01:30 UTC
When I download and run the Windows 64-bit version  of the latest 0.9.0 Pareto UI and try the default scenario (Strategic Permian Demo), using all defaults in Optimization Setup and not adding any data inputs, I get the following error

<img width="563" alt="image" src="https://github.com/project-pareto/pareto-ui/assets/420923/f4065cda-29e4-4531-86fa-f9cd48cbbbd7">

I probably had an earlier version installed, but I think that is a normal situation so even if that's the cause, it's still a bug.

**Comment by MichaelPesce** [comment] 2024-01-11 12:47
I'm thinking this is occurred for one of 2 reasons. Either the input excel sheet used was an older version, or the up-to-date input excel sheets have been updated since the 0.9.0 release. Due to the nature of how we read the data in from the excel sheets (by reading all tabs at once), if the UI isn't updated accordingly with the excel sheets, the function to read the data usually fails.

**Comment by tarnold17** [comment] 2024-01-11 17:12
@dangunter with a fresh install of the UI this morning, I am also getting an error, but it's different than the error you are seeing:

![image](https://github.com/project-pareto/pareto-ui/assets/26798258/44596688-5192-40c7-b949-9653d929ea4e)

The cause of this error is known - it's because of [this PR](https://github.com/project-pareto/project-pareto/pull/281) which merged yesterday and changed the way that one of the parameters is indexed (parameter `p_delta_Disposal` which corresponds to spreadsheet tab "DisposalCapacityIncrements"). This error should be resolved once we build a version of the UI with the latest version of the backend.

As for the error message you saw Dan, I am not sure why that would have happened. The latest version of strategic_permian_demo.xlsx does have a worksheet named "ROA", although there is not any data in that worksheet:

![image](https://github.com/project-pareto/pareto-ui/assets/26798258/2934ee91-f106-43d5-a3fc-9e108f2b1c81)

**Comment by MichaelPesce** [comment] 2024-01-31 17:45
fixed with the latest release #59

**Closed by MichaelPesce** 2024-01-31 17:45 UTC
Labels: Priority:High, bug
